### ISSUE TITLE
Error: Evaluation failed: TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by jaimeiniesta** [dequelabs/axe-core-npm#159]
Hi! I've found an issue when evaluating a site with axe-core/puppeteer. We're using these versions:

```
{
  "dependencies": {
    "@axe-core/puppeteer": "^4.0.0",
    "axe-core": "^4.0.2",
    "puppeteer": "^5.4.1"
  }
}
```

I've seen that support for puppeteer 5 is not official yet (although it seems to work fine with other URLs), I've also tried with puppetteer 4 and 3 but it also crashes with these versions.

The script I'm using is the same one as in the README for this package, but with this URL being checked:

```js
const { AxePuppeteer } = require('@axe-core/puppeteer');
const puppeteer = require('puppeteer');
 
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setBypassCSP(true);
 
  await page.goto('http://web.prm.ox.ac.uk/england/');
 
  const results = await new AxePuppeteer(page).analyze();
  console.log(results);
 
  await page.close();
  await browser.close();
})();
```

**Crash with puppetteer 5.4.1:**

```
(node:36312) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Right-hand side of 'instanceof' is not callable
    at getRootNode (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:10359:20)
    at new Context (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:10371:89)
    at Object.runRules [as _runRules] (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:11768:21)
    at Object.run (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:11961:13)
    at runAxe (__puppeteer_evaluation_script__:2:23)
    at ExecutionContext._evaluateInternal (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Crash with puppeteer 4.0.1:**

```
(node:36534) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Right-hand side of 'instanceof' is not callable
    at getRootNode (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:10359:20)
    at new Context (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:10371:89)
    at Object.runRules [as _runRules] (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:11768:21)
    at Object.run (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:11961:13)
    at runAxe (__puppeteer_evaluation_script__:2:23)
    at ExecutionContext._evaluateInternal (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/helper.js:116:19)
    at DOMWorld.evaluate (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/DOMWorld.js:108:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/helper.js:116:19)
    at AxePuppeteer.<anonymous> (/Users/jaime/code/axe-core-puppeteer-example/node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:178:53)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jaime/code/axe-core-puppeteer-example/node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Crash with puppeteer 3.3.0:**

```
(node:36701) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Right-hand side of 'instanceof' is not callable
    at getRootNode (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:10359:20)
    at new Context (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:10371:89)
    at Object.runRules [as _runRules] (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:11768:21)
    at Object.run (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:11961:13)
    at runAxe (__puppeteer_evaluation_script__:2:23)
    at ExecutionContext._evaluateInternal (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.evaluate (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/helper.js:94:19)
    at AxePuppeteer.<anonymous> (/Users/jaime/code/axe-core-puppeteer-example/node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:178:53)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jaime/code/axe-core-puppeteer-example/node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is crashing both in AWS Lambda (node 10) as in my Mac development machine (node 14.13.0).

**Comment by jaimeiniesta** [comment]
Another example for another URL in the same server, and a different crash this time.

**Cheking http://web.prm.ox.ac.uk/tibet/ **

```
(node:45772) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'source' of undefined
    at /Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:12096:35
    at Array.map (<anonymous>)
    at /Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:12094:59
    at Array.forEach (<anonymous>)
    at /Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:12093:14
    at Array.forEach (<anonymous>)
    at normalizeRelatedNodes (/Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:12087:34)
    at /Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:12147:17
    at Array.map (<anonymous>)
    at /Users/jaime/code/axe-core-puppeteer-example/node_modules/axe-core/axe.js:12129:51
    at ExecutionContext._evaluateInternal (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.evaluate (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/jaime/code/axe-core-puppeteer-example/node_modules/puppeteer/lib/helper.js:94:19)
    at AxePuppeteer.<anonymous> (/Users/jaime/code/axe-core-puppeteer-example/node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:178:53)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jaime/code/axe-core-puppeteer-example/node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:45772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by straker** [comment]
It appears that the first page is using a really old version of mootols (v1.11) which redefines `window.Document`. This causes it to no longer be a function but equal to the `document` object

```js
window.Document === window.document // true
```

As such, our code fails as `instanceof` cannot be used with an object

**Comment by straker** [comment]
The second bug is also a problem with overriding native features, this time with `Array.prototype.push`. `tibet.js` does this:

```js
// http://www.dustindiaz.com/top-ten-javascript/ 

Array.prototype.push = function(value) {
  this[this.length] = value;
}
```

which means when we try to `push` a spread of an array, it ends up with `undefined` instead of nulling out like normal:

```
let foo = [];
foo.push(...[])  // should do nothing but instead pushes `undefined`
```

**Comment by michael-siek** [comment]
Closing due to the sites being scanned are using an older version of mootools which redefines `window.Document` and the other site modify native functions.
