### ISSUE TITLE
[@axe-core/cli] chromedriver related bug

### ISSUE THREAD

**Issue by ktw1016** [dequelabs/axe-core-npm#203]
node: v12.9.0
axe: v4.1.1

running following commands:
```
// These are for setting permission to install axe-core/cli globally. Not sure if this has an impact on the error
npm set prefix ~/.npm
PATH="$HOME/.npm/bin:$PATH"
PATH="./node_modules/.bin:$PATH"

npm install @axe-core/cli -g
axe https://www.google.ca/
```

Running that results this:
```
Running axe-core 4.1.2 in chrome-headless
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/test-image-user/.npm/lib/node_modules/@axe-core/cli/node_modules/chromedriver/lib/chromedriver/chromedriver ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./chromedriver',
  path: './chromedriver',
  spawnargs: [ '--port=55994' ]
}
```

Just to make sure chromedriver path is correct, I tried the following, which results the exact same error, just with different chromedriver path.
```
wget https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
axe https://www.google.ca/ --chromedriver-path ./chromedriver
```

Is this a bug coming from axe, or am I missing something?

**Comment by Zidious** [comment]
Closing due to inactivity, please re-open is issue is apparent in version: 4.4.1
