### ISSUE TITLE
CLI: unable to execute `@axe-core/cli`

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-npm#229]
When using `@axe-core/cli@next` I am getting an error where axe is unable to find `axe.js`
```console
(node:41199) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/@axe-core/cli/dist/src/lib/node_modules/axe-core/axe.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.getAxeSource (/usr/local/lib/node_modules/@axe-core/cli/dist/src/lib/utils.js:82:15)
    at /usr/local/lib/node_modules/@axe-core/cli/dist/src/bin/index.js:20:30
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@axe-core/cli/dist/src/bin/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@axe-core/cli/dist/src/bin/index.js:4:12)
    at Command.cli (/usr/local/lib/node_modules/@axe-core/cli/dist/src/bin/index.js:17:28)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/@axe-core/cli/node_modules/commander/index.js:922:31)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41199) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:41199) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by padmavemulapati** [comment]
Verified as part of axe-core-npm QA, not able to reproduce. Now its working fine
