### ISSUE TITLE
Bug: Cannot find `node_modules/@axe-core/cli/node_modules/axe-core/axe.js`

### ISSUE THREAD

**Issue by jasikpark** [dequelabs/axe-core-npm#306]
Product: <<cli | puppeteer | react | reporter-earl | webdriverio | webdriverjs>>

CLI

Expectation: << Describe what you expect the product to do >>

Successfully connect to URL and test the page

Actual: << Describe what the product actually does >>

<details>
<summary>
Fails because it cannot find <code>/node_modules/@axe-core/cli/node_modules/axe-core/axe.js</code>
</summary>
<pre><code>
$ axe 'http://localhost:3000' --exit
node:fs:582
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/node_modules/axe-core/axe.js'
    at Object.openSync (node:fs:582:3)
    at Object.readFileSync (node:fs:450:35)
    at Object.getAxeSource (/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/lib/utils.js:82:15)
    at /Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/bin/index.js:20:30
    at Generator.next (<anonymous>)
    at /Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/bin/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/bin/index.js:4:12)
    at Command.cli (/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/bin/index.js:17:28)
    at Command.listener [as _actionHandler] (/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/node_modules/commander/index.js:922:31) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/node_modules/axe-core/axe.js'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node/16.5.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js lint:a11y:local
Directory: /Users/calebjasik/Github/astro/docs
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
astro on  main [$!] via  v16.5.0 took 2s 
✗  yarn workspace docs lint:a11y      
yarn workspace v1.22.10
yarn run v1.22.10
$ start-test 'yarn start --silent' 3000 'yarn lint:a11y:local'
1: starting server using command "yarn start --silent"
and when url "[ 'http://localhost:3000' ]" is responding with HTTP status code 200
running tests using command "yarn lint:a11y:local"

$ astro dev --silent
$ axe 'http://localhost:3000' --exit
node:fs:582
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/node_modules/axe-core/axe.js'
    at Object.openSync (node:fs:582:3)
    at Object.readFileSync (node:fs:450:35)
    at Object.getAxeSource (/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/lib/utils.js:82:15)
    at /Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/bin/index.js:20:30
    at Generator.next (<anonymous>)
    at /Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/bin/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/bin/index.js:4:12)
    at Command.cli (/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/dist/src/bin/index.js:17:28)
    at Command.listener [as _actionHandler] (/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/node_modules/commander/index.js:922:31) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/calebjasik/Github/astro/node_modules/@axe-core/cli/node_modules/axe-core/axe.js'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed with exit code 1: yarn lint:a11y:local
    at makeError (/Users/calebjasik/Github/astro/node_modules/start-server-and-test/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/calebjasik/Github/astro/node_modules/start-server-and-test/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 1: yarn lint:a11y:local',
  command: 'yarn lint:a11y:local',
  escapedCommand: '"yarn lint:a11y:local"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node/16.5.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js lint:a11y
Directory: /Users/calebjasik/Github/astro/docs
Output:
</code></pre>
</details>
Motivation: << Describe why you want the behavior to be changed >>

I want the tool to work.

<pre><code>
axe-core version: X.Y.Z
@axe-core/[integration]: 4.2.2

- Node version: v16.5.0  
- Platform:   macOS 11.4
</code></pre>

**Comment by padmavemulapati** [comment]
Whenever I got these kind of errors, it usually asks to delete the old version `/node_modules/@axe-core/cli/node_modules/axe-core/axe.js` files and will need to update/install latest version. 
This workaround works for me many times.

**Comment by Zidious** [comment]
Closing due to inactivity, please re-open if the issue is apparent in 4.4.1

**Comment by jasikpark** [comment]
I am unaware of whether this is still an issue -- I haven't touched this in a while 👍
