### ISSUE TITLE
Problem with running axe-cli in Buddy CI/CD

### ISSUE THREAD

**Issue by palmiak** [dequelabs/axe-core-npm#307]
Product: CLI

Expectation: To work in buddy.works

Actual: It throws 
```
Loading assets
Executing command: axe wpowls.co --exit --verbose
Running axe-core 4.3.1 in chrome-headless
An error occurred while testing this page.
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/

Action failed: see logs above for details
```

**More details**
Using buddy.works (there is a free tier so it's possible to test it) I added an action:
- node (uses official docker image node 14)
- axe is installed with `npm install @axe-core/cli -g --unsafe-perm=true --allow-root`
- I try to run `axe wpowls.co --exit --verbose`

Any suggestions how I can debug this?

**Comment by gemal** [comment]
add `--show-errors --verbose` for better error message

**Comment by palmiak** [comment]
I got something like this:
```
Running axe-core 4.3.2 in chrome-headless
Error: "unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)" 
 $s WebDriverError: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at Object.throwDecodedError (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:642:13)
    at Executor.execute (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:568:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/
```

When setting up the environment I installed:
```
apt-get update
sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
apt-get update
apt-get install -y google-chrome-stable
apt-get install -y gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

npm install @axe-core/cli -g --unsafe-perm=true --allow-root
```

**Comment by Zidious** [comment]
Closing due to inactivity. Please re-open if the issue is apparent in 4.4.1.
