### ISSUE TITLE
axe-core/puppeteer, playwright and webdriverjs throwing error white executing the tests

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#343]
Installed latest axe-core/npm packages : 
`npm install @axe-core/puppeteer@next` and it installed , `@axe-core/puppeteer@4.2.3-alpha.175`
and noticed that all packages are upgraded to `axe-core - 4.3.3`
as well `axe-core/playwright and axe-core/webdriverjs` too
and installed required dependencies
implemented a test file:
```
const { AxePuppeteer } = require('@axe-core/puppeteer');
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setBypassCSP(true);

  await page.goto('https://dequeuniversity.com/demo/mars/');

  const results = await new AxePuppeteer(page).analyze();
  console.log(results);

  await page.close();
  await browser.close();
})();
```
getting error:
```
(node:28230) UnhandledPromiseRejectionWarning: TypeError: (intermediate value).flat is not a function
    at AxePartialRunner.<anonymous> (/Users/dq_user/Documents/puppeteerCore/node_modules/@axe-core/puppeteer/dist/axePartialRunner.js:29:74)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dq_user/Documents/puppeteerCore/node_modules/@axe-core/puppeteer/dist/axePartialRunner.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28230) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28230) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
similar error seeing for `@axe-core/playwright` too

and for `@axe-core/webdriverjs` , the error is:
```
(node:30414) UnhandledPromiseRejectionWarning: TypeError: this.driver.switchTo(...).parentFrame is not a function
    at AxeBuilder.<anonymous> (/Users/dq_user/Documents/webdriverjsCore/node_modules/@axe-core/webdriverjs/dist/index.js:250:69)
    at step (/Users/dq_user/Documents/webdriverjsCore/node_modules/@axe-core/webdriverjs/dist/index.js:33:23)
    at Object.throw (/Users/dq_user/Documents/webdriverjsCore/node_modules/@axe-core/webdriverjs/dist/index.js:14:53)
    at rejected (/Users/dq_user/Documents/webdriverjsCore/node_modules/@axe-core/webdriverjs/dist/index.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30414) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30414) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by padmavemulapati** [comment]
@michael-siek moving back to "In Progress" as I am seeing another kind of issue with callback.
Here is the error log:
```
(node:17566) UnhandledPromiseRejectionWarning: Error: Malformed type for "handle" parameter of command switchToWindow
Expected: string
Actual: undefined

For more info see https://w3c.github.io/webdriver/#dfn-switch-to-window

    at Object.validate (/Users/dq_user/Desktop/webdriverioCore/node_modules/devtools/build/utils.js:52:19)
    at Browser.wrappedCommand (/Users/dq_user/Desktop/webdriverioCore/node_modules/devtools/build/devtoolsdriver.js:98:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17566) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17566) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C(node:17566) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:136:11)
    at Object.rmdir (fs.js:671:14)
    at resolve (/Users/dq_user/Desktop/webdriverioCore/node_modules/chrome-launcher/dist/chrome-launcher.js:286:21)
    at new Promise (<anonymous>)
    at Launcher.destroyTmp (/Users/dq_user/Desktop/webdriverioCore/node_modules/chrome-launcher/dist/chrome-launcher.js:273:16)
    at ChildProcess.chrome.on (/Users/dq_user/Desktop/webdriverioCore/node_modules/chrome-launcher/dist/chrome-launcher.js:247:26)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:17566) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
 ```

**Comment by padmavemulapati** [comment]
Updating the current  issue with @axe-core/puppeteer
1.  install @axe-core/puppeteer@nexrt , globally and locally
(@axe-core/puppeteer-4.2.3-alpha.183)
 2. install puppeteer
3. install fs
4. create test.js
5. run with node test.js 

```
CMacBook-Pro:puppeteer dq_user$ node test.js
(node:44537) UnhandledPromiseRejectionWarning: Error: net::ERR_EMPTY_RESPONSE at https://dequeuniversity.com/demo/mars/
    at navigate (/Users/dq_user/Documents/puppeteerCore/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:44537) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44537) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by padmavemulapati** [comment]
Validated,  with the updated `@axe-core/*@4.2.3-alpha.191` as part of regression testing  and working as expected.
