### ISSUE TITLE
CLI fails in Docker without en error

### ISSUE THREAD

**Issue by scythargon** [dequelabs/axe-core-npm#493]
Hello! Help me please:) 

<pre><code>
root@774035eb4120:/code# yarn axe  --chrome-options="no-sandbox,disable-setuid-sandbox,disable-dev-shm-usage" http://server:3000/\?localConfig\=1\&noAnimation\=1\&keepTeaser\=1 --verbose
yarn run v1.22.18
$ axe --load-delay=5000 --chrome-options=no-sandbox,disable-setuid-sandbox,disable-dev-shm-usage 'http://server:3000/?localConfig=1&noAnimation=1&keepTeaser=1' --verbose
Running axe-core 4.4.1 in chrome-headless
An error occurred while testing this page.
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@774035eb4120:/code# curl "http://server:3000/?localConfig=1&noAnimation=1&keepTeaser=1" | head -5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
<!DOCTYPE html>    0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
1<html lang="en">
0<head>
0  <meta charset="utf-8"/>
   <link rel="shortcut icon" href="/favicon.ico"/>
 5630  100  5630    0     0   785k      0 --:--:-- --:--:-- --:--:--  785k
(23) Failed writing body
root@774035eb4120:/code#

axe-core version: X.Y.Z
"@axe-core/cli": "^4.4.2",

node --version
v16.13.1

- Platform:  based on arm64v8/ubuntu:20.04 Docker image
</code></pre>

Any thoughts would be much appreciated!

**Comment by Zidious** [comment]
Hey @scythargon, 

Apologies for the delay, 


Could you rerun this example but add the flag `--show-errors` to see if the CLI will produce a stack trace.

**Comment by Zidious** [comment]
Closing due to inactivity, please re-open if the issue is apparent in 4.4.1

**Comment by jeffmagill** [comment]
Not OP, but I'm getting this too.

Installed via,

```bash
yarn global add @axe-core/cli
```

```bash
% axe --stdout --verbose --show-errors https://www.google.com 
Error: Error: Invalid URL: http:/
    at getRequestOptions (/Users/jeffmagill/.config/yarn/global/node_modules/selenium-webdriver/http/index.js:51:11)
    at new HttpClient (/Users/jeffmagill/.config/yarn/global/node_modules/selenium-webdriver/http/index.js:90:21)
    at getStatus (/Users/jeffmagill/.config/yarn/global/node_modules/selenium-webdriver/http/util.js:38:18)
    at checkServerStatus (/Users/jeffmagill/.config/yarn/global/node_modules/selenium-webdriver/http/util.js:76:14)
    at /Users/jeffmagill/.config/yarn/global/node_modules/selenium-webdriver/http/util.js:74:5
    at new Promise (<anonymous>)
    at Object.waitForServer (/Users/jeffmagill/.config/yarn/global/node_modules/selenium-webdriver/http/util.js:57:10)
    at /Users/jeffmagill/.config/yarn/global/node_modules/selenium-webdriver/remote/index.js:251:24
    at new Promise (<anonymous>)
    at /Users/jeffmagill/.config/yarn/global/node_modules/selenium-webdriver/remote/index.js:246:20
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/

% axe -v
Running axe-core 4.4.2 in chrome-headless
No url was specified. Check `axe --help` for help

An error occurred while testing this page.
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/

% node --version
v18.0.0
% yarn --version
1.22.18
```

**Comment by Zidious** [comment]
Hey @jeffmagill, 

Thanks for reporting this issue. Although not directly related to Docker, please see https://github.com/dequelabs/axe-core-npm/issues/501. 

If you could use NodeJS LTS version 16. Let me know if you run into anymore issues.
