### ISSUE TITLE
WebDriverError Running Axe-CLI on Linux

### ISSUE THREAD

**Issue by bbertucc** [dequelabs/axe-core-npm#614]
Product: cli

Expectation: Run on my linux server

Actual: Throws this error:
```
Error: WebDriverError: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at Object.throwDecodedError (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:589:13)
    at Executor.execute (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:514:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: '#0 0x55a1199fa2c3 <unknown>\n' +
    '#1 0x55a11980383a <unknown>\n' +
    '#2 0x55a119829543 <unknown>\n' +
    '#3 0x55a119824546 <unknown>\n' +
    '#4 0x55a119862de6 <unknown>\n' +
    '#5 0x55a11986274f <unknown>\n' +
    '#6 0x55a11985ad63 <unknown>\n' +
    '#7 0x55a11982f7e3 <unknown>\n' +
    '#8 0x55a119830a21 <unknown>\n' +
    '#9 0x55a119a4818e <unknown>\n' +
    '#10 0x55a119a4b622 <unknown>\n' +
    '#11 0x55a119a2eaae <unknown>\n' +
    '#12 0x55a119a4c2a3 <unknown>\n' +
    '#13 0x55a119a22ecf <unknown>\n' +
    '#14 0x55a119a6c588 <unknown>\n' +
    '#15 0x55a119a6c706 <unknown>\n' +
    '#16 0x55a119a868b2 <unknown>\n' +
    '#17 0x7faebfa90402 <unknown>\n'
}
```

Motivation: Hopefully, I can run axe cli on my web server..

<pre><code>
axe-core version: 4.5.2
@axe-core/[integration]: cli
- Node version:v18.7.0
- Platform:  Linux
</code></pre>

**Comment by Zidious** [comment]
Hey @bbertucc, 

Thanks for reporting this issue, 

We will investigate and back to you as soon as possible.

**Comment by bbertucc** [comment]
Closing this issue. The solutions here solves my problem: https://github.com/dequelabs/axe-cli/issues/84#issuecomment-561700845
