### ISSUE TITLE
BUG: ESM support is throwing error for Puppeteer and webdriverio

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#717]
##Steps to reproduce:
1. Installed latest @axe-core/puppetter and @axe-core/webdriverio (npm install @axe-core/puppeteer@next)
2. Imported into test file as need to get support for `.mjs` files
Testfile (test.mjs) for puppeteer
```
import AxeBuilder from '@axe-core/playwright';
import playwright from'playwright';
import fs from'fs';

(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('http://qateam.dequecloud.com/attest/api/test.html');

  try {
    const results = await new AxeBuilder({ page }).analyze()
     fs.writeFile("./Testmjs.json", JSON.stringify(results, null,4),(err)=>
    {if(err){
        console.error(err);
        return;
        };
        console.log("File has been created");
    })
  } catch (e) {
    // do something with the error
  }
  await browser.close();
})();
```

and Testfile for @axe-core/webdriverio
```
import AxeBuilder from '@axe-core/webdriverio';
import { remote } from 'webdriverio';
import fs from 'fs';

(async () => {
  const client = await remote({
    logLevel: 'error',
    capabilities: {
      browserName: 'chrome'
    }
  });

  await client.url('http://qateam.dequecloud.com/attest/api/test.html');

  const builder = new AxeBuilder({ client });
  const results = await builder.analyze();
    fs.writeFile("./Testmjs.json", JSON.stringify(results, null,4),(err)=>
    {if(err){
        console.error(err);
        return;
        };
        console.log("File has been created");
    })
   client.deleteSession();
})();
```
3. run this tests using `node --experimental-modules test.mjs`

Product:  puppeteer  & webdriverio 

Expectation: Should successfully run the test and gives the output in specified `.json` file

Actual: 
**Issue on puppeteer**
```
MacBook-Pro:puppeteer dq_user$ node --experimental-modules test.mjs

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

file:///Users/dq_user/Documents/axe-core-integrations/axe-core-npm/puppeteer/node_modules/@axe-core/puppeteer/dist/index.mjs:132
    const pathFile = __require.resolve("axe-core");
                               ^

TypeError: __require.resolve is not a function
    at frameSourceInject (file:///Users/dq_user/Documents/axe-core-integrations/axe-core-npm/puppeteer/node_modules/@axe-core/puppeteer/dist/index.mjs:132:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AxePuppeteer.analyzePromise (file:///Users/dq_user/Documents/axe-core-integrations/axe-core-npm/puppeteer/node_modules/@axe-core/puppeteer/dist/index.mjs:330:5)
    at async AxePuppeteer.analyze (file:///Users/dq_user/Documents/axe-core-integrations/axe-core-npm/puppeteer/node_modules/@axe-core/puppeteer/dist/index.mjs:310:26)
    at async file:///Users/dq_user/Documents/axe-core-integrations/axe-core-npm/puppeteer/test.mjs:12:20

Node.js v18.7.0
```

<img width="948" alt="image" src="https://user-images.githubusercontent.com/47409579/235463302-7d1a1f67-79b7-40e1-b765-d42cbd530b33.png">

**Issue on Webdriverio**
```
MacBook-Pro:webdriverio dq_user$ node --experimental-modules test.mjs
(node:3694) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///Users/dq_user/Documents/axe-core-integrations/axe-core-npm/webdriverio/node_modules/@axe-core/webdriverio/dist/index.mjs:184
      const sourceDir = __require.resolve("axe-core");
                                  ^

TypeError: __require.resolve is not a function
    at new AxeBuilder (file:///Users/dq_user/Documents/axe-core-integrations/axe-core-npm/webdriverio/node_modules/@axe-core/webdriverio/dist/index.mjs:184:35)
    at file:///Users/dq_user/Documents/axe-core-integrations/axe-core-npm/webdriverio/test.mjs:15:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.7.0
```
<img width="969" alt="image" src="https://user-images.githubusercontent.com/47409579/235463212-85b6583a-9642-4df0-84e3-607e5589165f.png">

Motivation: As ESM support implemented, need to test the `axe-core-npm` APIs using `.mjs` files

 - axe-core version: 4.7.0
- @axe-core/puppeteer and @axe-core/webdriverio: 4.7.1-alpha.383
- Node version: 18.7.0  
- Platform:  MacOS-11.6.8

**Comment by SantoshDeque** [comment]
Verified in latest build (4.7.1-alpha.384) issue is fixed for puppeteer and webdriverio.
 

https://user-images.githubusercontent.com/45222788/235890948-840a4042-285e-4a57-9e01-8f3c1c8be62a.mov
