### ISSUE TITLE
axe-core/cli shouldn't require -a on fresh install

### ISSUE THREAD

**Issue by plcj** [dequelabs/axe-core-npm#726]
Product: cli

Expectation:

Execute `axe https://www.duckduckgo.com` after being installed with `npm install @axe-core/cli -g`

Actual:

```
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/node_modules/axe-core/axe.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getAxeSource (/Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/@axe-core/cli/dist/cli.js:106:28)
    at Command.cli (/Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/@axe-core/cli/dist/cli.js:318:20)
    at Command.listener [as _actionHandler] (/Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/@axe-core/cli/node_modules/commander/lib/command.js:482:17)
    at /Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/@axe-core/cli/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/@axe-core/cli/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/@axe-core/cli/node_modules/commander/lib/command.js:1283:27)
    at Command.parse (/Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/@axe-core/cli/node_modules/commander/lib/command.js:909:10)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/@axe-core/cli/dist/cli.js:464:9) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/me/.nvm/versions/node/v16.15.0/lib/node_modules/node_modules/axe-core/axe.js'
}
```

Motivation:

axe core cli shouldn't require -a after a fresh install

<pre><code>
axe-core version: 4.7.0? if it's different from the @axe-core/cli version, I don't know how to find it
@axe-core/[integration]: 4.7.0

- Node version: v16.15.0  
- Platform:  macOS 13.3.1 (a) - I didn't collect all the details for it but I reproduced this on Ubuntu 22.04.2 where node was installed by apt, without nvm

</code></pre>

**Comment by daviddarke** [comment]
Hitting this issue as well. Confused about how to actually get the CLI to run/work.

**Comment by padmavemulapati** [comment]
On revert ESM , we can overcome this error
Valdiated with the latest canary build for `@axe-core/cli` (4.7.2-alpha.390) and its using chromedriver version - 114.0.5735.90

```
MacBook-Pro:cli dq_user$ axe www.google.com --browser chrome
Running axe-core 4.7.2 in chrome
Error: Error: Server was killed with SIGKILL
    at /usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/remote/index.js:260:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/

MacBook-Pro:cli dq_user$ axe www.google.com --browser chrome
Running axe-core 4.7.2 in chrome

Testing http://www.google.com ... please wait, this may take a minute.

  Violation of "aria-allowed-role" with 1 occurrences!
    Ensures role attribute has an appropriate value for the element. Correct invalid elements at:
     - #APjFqb
    For details, see: https://dequeuniversity.com/rules/axe/4.7/aria-allowed-role

  Violation of "aria-valid-attr-value" with 2 occurrences!
    Ensures all ARIA attributes have valid values. Correct invalid elements at:
     - #APjFqb
     - .ayzqOc
    For details, see: https://dequeuniversity.com/rules/axe/4.7/aria-valid-attr-value

  Violation of "color-contrast" with 8 occurrences!
    Ensures the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds. Correct invalid elements at:
     - .uU7dJb
     - .AghGtd > .pHiOh:nth-child(1)
     - .AghGtd > .pHiOh:nth-child(2)
     - .pHiOh:nth-child(3)
     - .pHiOh:nth-child(4)
     - .iTjxkf > .pHiOh:nth-child(1)
     - .iTjxkf > .pHiOh:nth-child(2)
     - .ayzqOc
    For details, see: https://dequeuniversity.com/rules/axe/4.7/color-contrast

  Violation of "region" with 8 occurrences!
    Ensures all page content is contained by landmarks. Correct invalid elements at:
     - .gb_Bd > div:nth-child(1)
     - .gb_oa
     - .lnXdpd
     - #SIvCob
     - .uU7dJb
     - .AghGtd
     - .iTjxkf > .pHiOh:nth-child(1)
     - .iTjxkf > .pHiOh:nth-child(2)
    For details, see: https://dequeuniversity.com/rules/axe/4.7/region

19 Accessibility issues detected.
Testing complete of 1 pages

Please note that only 20% to 50% of all accessibility issues can automatically be detected. 
Manual testing is always required. For more information see:
https://dequeuniversity.com/curriculum/courses/testingmethods

MacBook-Pro:cli dq_user$ axe --version
4.7.2-alpha.390+0d0c9d1
```
