### ISSUE TITLE
axe-webdriverio does not work

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-npm#75]
Axe-webdriverio hasn't been updated in 3 years and is out-of-date with latest webriverio changes. 

Here's the problem: axe-webdriverio is a wrapper around axe-webdriverjs and does that by bridging the webdriverio functions to webdriverjs functionality (https://github.com/dequelabs/axe-core-npm/blob/develop/packages/webdriverio/lib/bindings.js). However, the functions it tries to wrap are no longer available in webdriverio (element and frame do not exist anymore). This causes webdriverjs to fail when injecting axe into iframes as those functions do not exist on the driver (https://github.com/dequelabs/axe-webdriverjs/blob/develop/lib/axe-injector.js#L62-L91)

Theoretically the fix should be to wrap the correct functions (`findElement` and `switchToFrame`), but we should add proper integration tests to make sure this truly works as right now there is only a single unit test. Also, the unit test is bad because it uses a mock driver, meaning updating to v6 of webdriverio (which should fail) is passing the tests still.

If you test with an actual browser instance you'll see it failing:

```js
const bindings = require('../lib/bindings');
const { remote } = require('webdriverio');

let browser;
before(async () => {
  browser = await remote({
    logLevel: 'trace',
    capabilities: {
        browserName: 'chrome'
    }
  });
});
```

**Comment by jeeyyy** [comment]
Related issue - https://github.com/dequelabs/axe-core-npm/issues/58

**Comment by padmavemulapati** [comment]
Tried to execute a testscript - with simple analyse() api, its resulting with error: saying 
```
MacBook-Pro:webdriverio dq_user$ node test.js
2021-03-03T11:29:34.761Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2021-03-03T11:29:34.762Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900
2021-03-03T11:29:35.289Z INFO devtools: Connect Puppeteer with browser on port 51205
2021-03-03T11:29:35.737Z INFO devtools: COMMAND navigateTo("http://qateam.dequecloud.com/attest/api/test.html")
2021-03-03T11:29:38.506Z INFO devtools: RESULT null
(node:6622) UnhandledPromiseRejectionWarning: TypeError: driver.executeAsyncScript is not a function
    at /Users/dq_user/Documents/axecorenpmwdio/axe-core-npm/node_modules/@axe-core/webdriverjs/dist/index.js:152:14
    at /Users/dq_user/Documents/axecorenpmwdio/axe-core-npm/node_modules/@axe-core/webdriverjs/dist/axe-injector.js:441:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6622) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
@michael-siek please review it

**Comment by padmavemulapati** [comment]
Validated with the latest @axe-core/webdriverio (@axe-core/webdriverio@4.0.0-alpha.13)
working as expected, but with little enhancement in documentation required, (https://github.com/dequelabs/axe-core-npm/issues/216)
As it is not effecting the current ticket moving it to docs column

**Comment by s-plum** [comment]
Following this issue as I am hitting a similar error. I tried this out with the test script listed in #216 and fresh installs of all dependencies, and I am still hitting the following error when I run with `node test.js` (replaced my local file path with `user/path`):
```
/Users/user/path/node_modules/@axe-core/webdriverjs/dist/index.js:152
      driver.executeAsyncScript(function (context, options, config) {
             ^

TypeError: driver.executeAsyncScript is not a function
    at /Users/user/path/node_modules/@axe-core/webdriverjs/dist/index.js:152:14
    at /Users/user/path/node_modules/@axe-core/webdriverjs/dist/axe-injector.js:441:18
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
Using:
- node v15.12.0
- @axe-core/webdriverio v4.0.0-alpha.13
- chromedriver v89.0.0
- selenium-webdriver v4.0.0-beta.2
- webdriverio v7.2.2

Please let me know if there is additional documentation that I am missing to get this running properly!

**Comment by padmavemulapati** [comment]
@s-plum , can you please give a try with webdriverio v 6.x.x

**Comment by s-plum** [comment]
@padmavemulapati Using these versions works as expected, thank you!
