### ISSUE TITLE
BUG: Getting error when trying to implement "logToConsole(..)"

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-npm#858]
### Product

react

### Product Version

4.7.4-62fd241.0

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
logToConsole(axeResults), should  return  axe-results

#### Actual
Giving Error:
```
console.group
      New axe issues

      at Function.logToConsole (node_modules/@axe-core/react/dist/index.js:284:11)

 FAIL  src/App.test.js
  ✕ renders learn react link (44 ms)

  ● renders learn react link

    TypeError: Cannot read properties of undefined (reading 'forEach')

       6 | test('renders learn react link', () => {
       7 |   const result = render(<App />);
    >  8 |   axe.logToConsole(result);
         |       ^
       9 |   
      10 | });
      11 |

      at Function.logToConsole (node_modules/@axe-core/react/dist/index.js:285:22)
      at Object.<anonymous> (src/App.test.js:8:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.774 s, estimated 2 s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```

#### How to Reproduce
Tried with React 

1. React code - App.test.js
```
import App from './App';
import axe from '@axe-core/react';


test('renders learn react link', () => {
  const result = render(<App />);
  axe.logToConsole(result);

});
```

```App.js
import React from 'react';
import Button from './Button.mjs';


const App = () => {
  const handleClick = () => {
    alert('Button clicked!');
  };

  return (
    <div>
      <h1>Welcome to my app</h1>
      <Button onClick={handleClick}>Click me</Button>
    </div>
  );
};

export default App;

```
Issues:
```
console.group
      New axe issues

      at Function.logToConsole (node_modules/@axe-core/react/dist/index.js:284:11)

 FAIL  src/App.test.js
  ✕ renders learn react link (44 ms)

  ● renders learn react link

    TypeError: Cannot read properties of undefined (reading 'forEach')

       6 | test('renders learn react link', () => {
       7 |   const result = render(<App />);
    >  8 |   axe.logToConsole(result);
         |       ^
       9 |   
      10 | });
      11 |

      at Function.logToConsole (node_modules/@axe-core/react/dist/index.js:285:22)
      at Object.<anonymous> (src/App.test.js:8:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.774 s, estimated 2 s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```
### Screenshot

![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/04960371-9d64-470a-88bc-085bb1e28d52)

It identified the function `logToConsole(result)` and started looking for the New issues - but unable to return the value

![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/a43fd264-3e17-4b91-8f47-205fe945504a)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-npm/react_|
|**Version** | _4.7.4-62fd241.0_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|

**Comment by padmavemulapati** [comment]
It is blocking the [release ](https://github.com/dequelabs/axe-core-npm/pull/846) as RC having the [feature](https://github.com/dequelabs/axe-core-npm/issues/802)

**Comment by padmavemulapati** [comment]
This is not actually an issue, but the way results rendered to console to specific requirement. i.e.,"Request: Export the default logToConsole logger" so that it cannt be considered as a feature, which can implement all over the packages.

It can be applicable only for the react-componants, those can be rendered to the browsers and browser's devtools console would be showing the logs for `New Issues`

Steps validated:

1. create a component 
```index.html
<!DOCTYPE html>
<html>
  <head> </head>
  <body>
    <div id="container"></div>
    <img src=""/>
    <style>
      * {
        padding: 0;
        margin: 0;
      }

      html {
        font: 14px normal Arial, sans-serif;
        color: #626771;
        background-color: #fff;
      }

      body {
        padding: 60px;
        text-align: center;
      }

      h1 {
        font-size: 18px;
        margin-bottom: 20px;
      }
    </style>
    <script src="dist/bundle.js"></script>
  </body>
</html>
```
2. configure the axe to the componant

```
const axeConf = {
  rules: [
    { id: 'heading-order', enabled: true },
    { id: 'label-title-only', enabled: true },
    { id: 'image-alt', enabled: true },
    { id: 'link-in-text-block', enabled: true },
    { id: 'region', enabled: true },
    { id: 'skip-link', enabled: true },
    { id: 'help-same-as-label', enabled: true }
  ]
};
```
3. Render the above react-componant via browser (here started the server on http://localhost:8081/) using 

```
if (process.env.NODE_ENV !== 'production') {
  axe(React, ReactDOM, 1000, axeConf);
  const axeResults = {} // get axe-results from somewhere

   axe.logToConsole(axeResults) // logs to the devtools console
}
```
Output: logToConsole() is logging the axeResults to browser's console(devtools)

![image](https://github.com/dequelabs/axe-core-npm/assets/47409579/2f5bdfbe-13a4-4a9c-9807-d8214b6703ca)


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-npm/react_|
|**Version** | _4.7.4-62fd241.0_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|
